# Generated by Django 5.2.11 on 2026-06-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('amount', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('is_fraud', models.BooleanField()),
                ('features_json', models.TextField(default='[]')),
            ],
        ),
    ]
